## reading the file

In [81]:
with open('one.txt') as mytext:  #here we are using jupyter , if we want to us google colab then have to paste the path of file
  print(mytext.read())

Abhishek
This is a story about dogs
our canine pet
dogs are funny animals



In [82]:
with open('two.txt') as mytext:  #here we are using jupyter , if we want to us google colab then have to paste the path of file
  print(mytext.read())

Data Science
This story is about surfing
catching waves is fun
surfing is a popular water sport



## reading entire text as a string

In [83]:
with open('one.txt') as mytext:
  entire_text=mytext.read()

In [84]:
entire_text

'Abhishek\nThis is a story about dogs\nour canine pet\ndogs are funny animals\n\x0c'

In [85]:
type(entire_text)

str

In [86]:
print(entire_text)

Abhishek
This is a story about dogs
our canine pet
dogs are funny animals



## reading each line as a list

In [87]:
with open('one.txt') as mytext:
  lines=mytext.readlines()

In [88]:
lines

['Abhishek\n',
 'This is a story about dogs\n',
 'our canine pet\n',
 'dogs are funny animals\n',
 '\x0c']

In [89]:
type(lines)

list

## reading in words separately

In [90]:
with open('one.txt') as f:
  words=f.read().split()

In [91]:
words

['Abhishek',
 'This',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pet',
 'dogs',
 'are',
 'funny',
 'animals']

In [92]:
with open('one.txt') as f:
  words=f.read().lower().split()   #lower function used

In [93]:
words

['abhishek',
 'this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pet',
 'dogs',
 'are',
 'funny',
 'animals']

In [94]:
with open('one.txt') as f:
  words=f.read().upper().split() 

In [95]:
words   

['ABHISHEK',
 'THIS',
 'IS',
 'A',
 'STORY',
 'ABOUT',
 'DOGS',
 'OUR',
 'CANINE',
 'PET',
 'DOGS',
 'ARE',
 'FUNNY',
 'ANIMALS']

In [96]:
words[2]  #all are element of list

'IS'

## building a vocabulary(creating a "bag of words")

In [97]:
with open('one.txt') as f:
  words_one=f.read().lower().split() 

In [98]:
words_one

['abhishek',
 'this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pet',
 'dogs',
 'are',
 'funny',
 'animals']

In [99]:
len(words_one)

14

In [100]:
var1=[3,4,7,4,9,6,1,7]
print(var1)
var2=set(var1)  #type casting
print(var2)     #set remove all the duplicate element

[3, 4, 7, 4, 9, 6, 1, 7]
{1, 3, 4, 6, 7, 9}


In [101]:
uni_words_one=set(words_one)    #type casting

In [102]:
len(uni_words_one)

13

In [103]:
with open('two.txt') as f:
  words_two=f.read().lower().split() 
  uni_words_two=set(words_two)

In [104]:
uni_words_two

{'a',
 'about',
 'catching',
 'data',
 'fun',
 'is',
 'popular',
 'science',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

# get all unique words across all documents

In [105]:
all_uni_words=set()
all_uni_words.update(uni_words_one)
all_uni_words.update(uni_words_two)

In [106]:
all_uni_words   #all unique words from both the doc

{'a',
 'abhishek',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'data',
 'dogs',
 'fun',
 'funny',
 'is',
 'our',
 'pet',
 'popular',
 'science',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [107]:
len(all_uni_words)

22

In [108]:
full_vocab=dict()   #with the help of dict. giving the index no.
i=0
for word in all_uni_words:
      full_vocab[word]=i
      i=i+1

In [109]:
full_vocab

{'this': 0,
 'fun': 1,
 'funny': 2,
 'story': 3,
 'pet': 4,
 'animals': 5,
 'popular': 6,
 'water': 7,
 'abhishek': 8,
 'about': 9,
 'a': 10,
 'is': 11,
 'catching': 12,
 'canine': 13,
 'waves': 14,
 'surfing': 15,
 'sport': 16,
 'our': 17,
 'science': 18,
 'data': 19,
 'dogs': 20,
 'are': 21}

## empty count per doc

In [30]:
# create an empty vector with space for each word in the vocabulary

In [31]:
one_freq=[0]*len(full_vocab)
two_freq=[0]*len(full_vocab)
all_words=['']*len(full_vocab)

In [32]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [33]:
two_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [34]:
all_words

['',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

In [110]:
for word in full_vocab:
    word_ind=full_vocab[word]
    all_words[word_ind]=word

In [111]:
all_words

['this',
 'fun',
 'funny',
 'story',
 'pet',
 'animals',
 'popular',
 'water',
 'abhishek',
 'about',
 'a',
 'is',
 'catching',
 'canine',
 'waves',
 'surfing',
 'sport',
 'our',
 'science',
 'data',
 'dogs',
 'are']

## counts per word per document

In [115]:
# map the frequencies for each word in one.txt to our vector
with open('one.txt') as f:
  one_text=f.read().lower().split() 

for word in one_text:
    word_ind=full_vocab[word]
    one_freq[word_ind]+=1

In [116]:
one_freq

[3, 0, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0, 3, 0, 0, 0, 3, 0, 0, 6, 3]

In [39]:
with open('two.txt') as f:
  two_text=f.read().lower().split() 

for word in two_text:
    word_ind=full_vocab[word]
    two_freq[word_ind]+=1

In [40]:
two_freq

[1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 3, 1, 0, 1, 2, 1, 0, 1, 1, 0, 0]

In [41]:
import pandas as pd

In [42]:
pd.DataFrame(data=[one_freq,two_freq],columns=all_words)

this  fun  funny  story  pet  animals  popular  water  abhishek  about  \
0     1    0      1      1    1        1        0      0         1      1   
1     1    1      0      1    0        0        1      1         0      1   

   ...  catching  canine  waves  surfing  sport  our  science  data  dogs  are  
0  ...         0       1      0        0      0    1        0     0     2    1  
1  ...         1       0      1        2      1    0        1     1     0    0  

[2 rows x 22 columns]

# Scikit-learns text feature extraction options

In [43]:
text=['This is a line',
    "This is another line",
"Completely different line"]

In [44]:
text

['This is a line', 'This is another line', 'Completely different line']

### count vectorizer

In [45]:
from sklearn.feature_extraction.text import TfidfTransformer , TfidfVectorizer, CountVectorizer

In [46]:
cv=CountVectorizer()  #pre defined files which is provided by Tfid

In [47]:
cv.fit_transform(text)

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [48]:
sparse_mat=cv.fit_transform(text)

In [49]:
sparse_mat.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]])

In [50]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [51]:
cv=CountVectorizer(stop_words='english') #remove basic word which do not have meaning

In [52]:
cv.fit_transform(text).todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]])

In [53]:
cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

### TfidfTransformer

In [54]:
#TfidfVerctorizer is used on sentence,while TfidfTransformer is used on an existing count matrix, such as one 
# returned by CountVectorizer

In [55]:
tfidf_transformer=TfidfTransformer()

In [56]:
cv=CountVectorizer()

In [57]:
counts=cv.fit_transform(text)

In [58]:
counts

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [59]:
tfidf=tfidf_transformer.fit_transform(counts)

In [60]:
tfidf.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [61]:
from sklearn.pipeline import Pipeline

In [62]:
pipe=Pipeline([('cv',CountVectorizer()),('tfidf',TfidfTransformer())])

In [64]:
results=pipe.fit_transform(text)

In [65]:
results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [66]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

### TfidfVectorizer

In [71]:
#Does both above in a single  step

In [72]:
tfidf=TfidfVectorizer()

In [73]:
new=tfidf.fit_transform(text)

In [74]:
new.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])