#Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([2,5,8])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
print('a= ',a)
print('a*6 =' ,a*6)

a=  [2 5 8]
a*6 = [12 30 48]


In [4]:
print('a= ',a)
print('a*a =' ,a*a)

a=  [2 5 8]
a*a = [ 4 25 64]


In [5]:
print('a= ',a)
print('a+a =' ,a+a)

a=  [2 5 8]
a+a = [ 4 10 16]


In [6]:
print('a= ',a)
print('a/3 =' ,a/3)

a=  [2 5 8]
a/3 = [0.66666667 1.66666667 2.66666667]


In [7]:
b=np.array([[1,3,5],[7,9,13]])

In [8]:
b

array([[ 1,  3,  5],
       [ 7,  9, 13]])

In [9]:
print(b)

[[ 1  3  5]
 [ 7  9 13]]


In [10]:
print(b.shape)

(2, 3)


In [11]:
#zeros
c=np.zeros((1,3))

In [12]:
c

array([[0., 0., 0.]])

In [13]:
print(c.shape)

(1, 3)


In [14]:
#ones
d=np.ones((3,3))

In [15]:
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
#constant value
e=np.full((3,3),7)

In [17]:
e

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [18]:
#eye diagonal value
f=np.eye((3))

In [19]:
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
##random number
h=np.random.random((2,3))

In [21]:
h

array([[0.50510845, 0.09779588, 0.84467292],
       [0.5315564 , 0.01594127, 0.93536273]])

In [22]:
#transpose
i=np.array([[2,5,3],[1,4,8]])

In [23]:
print('transpose of matrix  :',i.T)

transpose of matrix  : [[2 1]
 [5 4]
 [3 8]]


In [24]:
#ARANGE
j=np.arange(5,16)
print("a series of number ;", j)

a series of number ; [ 5  6  7  8  9 10 11 12 13 14 15]


In [25]:
j

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
#skipping
k=np.arange(1,11,2)

In [27]:
k

array([1, 3, 5, 7, 9])

In [28]:
l=np.arange(50,-1,-5)

In [29]:
l

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [30]:
print(l)

[50 45 40 35 30 25 20 15 10  5  0]


In [31]:
#linspace
m=np.linspace(1,10)
m

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
n=np.linspace(1,20,5)
n

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [37]:
#empty
print(np.empty((2,3)))

[[0.50510845 0.09779588 0.84467292]
 [0.5315564  0.01594127 0.93536273]]


In [35]:
print("Empty matrix\n-------------\n", np.empty((2,2)))

Empty matrix
-------------
 [[1.69311700e-313 0.00000000e+000]
 [1.87192224e-316 1.86186860e-316]]
